### ISSUE TITLE
It’s a piece of freakin trash

### ISSUE THREAD

**Issue by luixiuno** [pwn20wndstuff/MeridianJB#3]
It ALWAYS gives errors and it doesn’t pwn or install jailbreak or reboot or respring or install apt-get

No virus it’s just trash, because it leads to: https://totally-not.spyware.lol/ I am on iOS 13.5.0 tryna be a beta tester with unc0ver but I need to urgently jailbreak iOS 10.3.3 or 10.3.4 or I don’t know

And for the ones who want to say answer is cydia Impactor, well it’s BROKEN and my dad and I are not paying a lot and wait 2 months for them to activate the membership >:(

**Comment by luixiuno** [comment]
And I am NOT using another impactor that uses AltServer and won’t work

**Comment by PsychoTea** [comment]
I'm really struggling to see what your _actual_ issue is here.

Got to https://totally-not.spyware.lol on the 64-bit iOS 10.x device you want to jailbreak, slide the slider, and install it.

**Comment by luixiuno** [comment]
Ugh, this is closed because I am searching in every single store for 32 bit jb AND ITS REVOKED >:(

And now I get it, THIS IS FOR 64 BITS and it’s useful to me
